---
abstract: 'Simple L<KinoSearch1> Interface, inspired by the now depricated L<Plucene::Simple>'
author:
  - 'n0body <n0body@thisaintnews.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: KinoSearchX-Simple
no_index:
  directory:
    - inc
    - t
requires:
  Data::Page: 0
  KinoSearch1: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Test::More: 0
  namespace::autoclean: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
