---
abstract: 'Simple L<KinoSearch1> Interface, inspired by L<Plucene::Simple>'
author:
  - 'n0body <n0body@thisaintnews.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: KinoSearchX-Simple
no_index:
  directory:
    - inc
    - t
requires:
  KinoSearch1: 0
  Moose: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
